### ISSUE TITLE
Check if hostname is valid

### ISSUE THREAD

**Issue by Nawaar** [vaslabs/sbt-kubeyml#85]
It would be good if it checked whether the hostname in the ingress is valid first then getting an error later on:

`The Ingress "backend" is invalid: spec.rules[0].host: Invalid value: "runner-EcDQy-nU-project-306-concurrent-0": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

**Comment by vaslabs** [comment]
it just looks like we need to stop accepting upper case characters https://github.com/vaslabs/sbt-kubeyml/blob/master/src/main/scala/kubeyml/ingress/Protocol.scala#L63
and update the tests

**Comment by vaslabs** [comment]
version 0.3.4 , please test
